### ISSUE TITLE
English source text

### ISSUE THREAD

**Issue by brunobord** [brunobord/rad-hack#1]
Currently work in progress.

**Comment by brunobord** [comment]
ref: https://github.com/brunobord/the-black-hack/pull/48#issuecomment-252757848

> I've seen you are doing it officially. Do you want help?

Yes, help would be nice. Since I only have the printed book _and_ an earlier Google document (that has many differences with the final copy) it's a bit of hard work.
I've managed to transcribe the text down to the "Resting" section. How about you?

**Comment by fermcg** [comment]
I'm behind you, but I have the pdf version. I'll copy things after that point and send you.

**Comment by fermcg** [comment]
I've finished it (everything after "Resting" - all in markdown). The last table is a little buggy because the last entry is too long.

**Comment by fermcg** [comment]
Please let me know if it's ok. (just did a pull request)

**Comment by fermcg** [comment]
I've double checked my review searching for things where there are numeric discrepancies and potential typos. They are:

Your Versoin
| 11. Force Field       | All nearby allies gain 4 Armor Points for one minute. 

## My version reads 2 Armor Points

**Enemies** usually have 1 point of armor ... (All to a maximum of 10)

## my version ends with 10 AP (not plain 10) which is more explicit

| Weapon | Cost
| Heavy Melee   | 100  |

## My version has a cost of 20 (yours seems more plausible)

yours:

## Equipment quality & degradation

Whenever weapons ... cost of equipment by 5-20 Slugs ...

## mine reads ... cost of equipment by around 5-25 Slugs ...

## In your version, sometimes 'enemy' is typed with two 'n's (ennemy) - typo.

_If the characters lose the fight or are unable to recover the body of a character, they character is lost forever!_

## (I guess it's 'that character' not 'they')

your version
**Crippled** - STR and DEX

## my version: STR or DEX

**Comment by brunobord** [comment]
- [x] Force field
- [x] 10 Armor Points
- [x] Heavy Melee cost -- mine was correct
- [x] 5-25 slugs,
- [x] "ennemy" typo,
- [x] "their character",
- [x] Crippled STR and/or DEX
